firebolt-db/firebolt-node-sdk

- LICENSE
- README.md
Minor preparations to make this repo public.
> Minor updates to LICENSE and README

- README.md
- src/index.ts
Fixing README links so that they work on npm. Also removing links that point to missing sections.
> change nav links to html so that they work on npm

- src/index.ts
- src/statement/index.ts
- src/statement/stream/jsonStream.ts
- src/statement/stream/parser.test.ts
- src/statement/stream/parser.ts
This pr will add support for parsing multistatement sql responses using json streaming parser
> Multistatement responses

- .github/workflows/integration-tests.yaml
- src/formatter/index.ts
- src/statement/dataTypes.ts
- src/statement/hydrateResponse.ts
- test/integration/bytea.test.ts
- test/unit/statement.test.ts
> FIR-16956: Add support for bytea

- .github/workflows/integration-tests.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/release-v0.yaml
- .github/workflows/release-workflow.yaml
- .github/workflows/release.yaml
Integration test wf was already commented out so I kept it as is for now.
> ci: version split

- README.md
- src/service/database/index.ts
- src/service/database/model.ts
- src/service/database/types.ts
- src/service/engine/index.ts
- src/service/engine/model.ts
- src/service/engine/types.ts
- test/integration/engine.test.ts
- test/unit/database.test.ts
- test/unit/engine.test.ts
Now supporting creating and deleting databases and engines as well as attaching engines to databases
> feat: support create delete and attach database and engine

- README.md
Added an upper limit for 0.* node sdk version
> docs: npm install upper version limit

- README.md
Added a lower limit for 1.* node sdk version
> docs: npm install lower version limit

- .github/workflows/release-v0.yaml
- .github/workflows/release.yaml
Fix tag descriptions for v1 and v0 release actions
> fix tag parameters descriptions

- .github/workflows/integration-tests-v1.yaml
- .github/workflows/integration-tests-v2.yaml
- .github/workflows/integration-tests.yaml
- test/integration/v2/engine.test.ts
Fixed the `environment` parameter in workflow_call
> ci: fix integration-tests-v2 workflow file

- package-lock.json
- package.json
- src/http/node.ts
- test/integration/v1/boolean.test.ts
- test/integration/v1/long.test.ts
- test/integration/v2/long.test.ts
This PR implements two jira issues
- Remove advanced_mode usage https://packboard.atlassian.net/browse/FIR-28040
- Improve long running test https://packboard.atlassian.net/browse/FIR-29098
> Fir 28440 remove advanced mode

- src/common/errors.ts
- src/connection/connection_v2.ts
- test/integration/v2/index.test.ts
- test/unit/v2/connection.test.ts
Add a helpful message on account resolution 404 error message
> Fir 28768 missing account error

- src/statement/hydrateResponse.ts
- test/integration/v1/infNan.test.ts
- test/integration/v2/infNan.test.ts
- test/unit/statement.test.ts
Added parsing of inf and nan values. Added unit and integration tests
> test: Fir 29924 add inf and nan tests in node sdk

- test/integration/v1/long.test.ts
- test/integration/v2/long.test.ts
Added long query test execution time measurement and verification that it's more than 350sec.
> test: add runtime validation for long tests

- src/formatter/index.ts
- test/integration/v1/bytea.test.ts
- test/integration/v2/bytea.test.ts
- test/unit/statement.test.ts
Updated bytea formatting according to recent changes
> fix: Fir 30653 update bytea formatting in node sdk

- test/integration/v1/index.test.ts
Removed `use_standard_sql` parameter usage from tests
> test: remove use_standard_sql usage

- src/connection/base.ts
- src/formatter/index.ts
- test/integration/v2/setStatement.test.ts
- test/unit/connection.test.ts
- test/unit/statement.test.ts
Added support for client-side set statements parsing and execution
> feat: Fir 29768 add support for set statements in node sdk

- src/connection/base.ts
- src/connection/connection_v1.ts
- src/connection/connection_v2.ts
- src/service/database/index.ts
- src/service/engine/index.ts
- test/integration/v2/engine.test.ts
- test/integration/v2/infraV2.test.ts
Added resource manager integration tests for v2 infra account
Added create engine and database parameters validation and translation
> tests: Resource manager v2 testing

- src/service/engine/index.ts
- src/service/engine/types.ts
- test/integration/v2/engine.test.ts
- test/unit/v2/engine.test.ts
Added initially_stopped engine option support
> feat: Engine intially stopped option

- src/service/engine/index.ts
- src/service/engine/model.ts
- src/service/engine/types.ts
- test/unit/v2/database.test.ts
- test/unit/v2/engine.test.ts
Fixed engines parsing in methods:
- engineService.getByName
- engineService.getAll
- engineService.getByDB
> fix: Fix engine status parsing for engine get metods

- src/connection/connection_v2.ts
- src/service/engine/model.ts
- test/integration/v1/bytea.test.ts
- test/integration/v1/date.test.ts
- test/integration/v1/systemEngine.test.ts
- test/integration/v2/bytea.test.ts
- test/integration/v2/date.test.ts
- test/integration/v2/index.test.ts
- test/integration/v2/infraV2.test.ts
- test/integration/v2/systemEngine.test.ts
- test/unit/v2/engine.test.ts
> refactor: Quoted identifiers

- test/integration/v2/engine.test.ts
We no longer have engines v1 so removing the test case for it.
Also, fix formatting.
> test: Remove engine v1 options

- test/integration/v2/engine.test.ts
Verified fixes the error we're having in main right now.
> test: Increase timeout for engine tests

- src/auth/index.ts
- src/common/tokenCache.ts
- src/connection/connection_v2.ts
- test/unit/connection.test.ts
- test/unit/v2/connection.test.ts
- test/unit/v2/engine.test.ts
Added caching for account info and system engine url data
> feat: Fir 33388 cache account id and system engine url in node sdk

- src/service/database/index.ts
- test/integration/v2/engine.test.ts
- test/integration/v2/systemEngine.test.ts
- test/unit/v2/database.test.ts
Use `I_S.catalogs` table in resource manager if it exists.
> feat: Fir 33645 replace i s databases with i s catalogs in drivers for node sdk

- .github/workflows/integration-tests-v2.yaml
- test/integration/v2/account.test.ts
- test/integration/v2/auth.test.ts
- test/integration/v2/boolean.test.ts
- test/integration/v2/bytea.test.ts
- test/integration/v2/database.test.ts
- test/integration/v2/date.test.ts
- test/integration/v2/engine.test.ts
- test/integration/v2/index.test.ts
- test/integration/v2/infNan.test.ts
- test/integration/v2/infraV2.test.ts
- test/integration/v2/long.test.ts
- test/integration/v2/outputFormat.test.ts
- test/integration/v2/setStatement.test.ts
- test/integration/v2/stream.test.ts
- test/integration/v2/systemEngine.test.ts
This fixes our tests and runs all existing ones against new account v2.
> test: Remove obsolete v1 engine tests

- .github/workflows/integration-tests-v2.yaml
- package-lock.json
This lets us run centralised tests from the ecosystem CI repo.
> ci: Allow calling tests from another repo

- .github/workflows/docs-lint-and-validate.yaml
This allows a new workflow to be scheduled from a branch.
> ci(NoTicket): create new workflow for testing

- README.md
Recent user issues warrant adding a new section to the README to address special considerations when using the Firebolt Node.js SDK.
> docs(FIR-45553): Add special consideration readme section
