src/formatter/index.ts
test/unit/statement.test.ts

Comments no longer removed from queries. As that was only done done to make parameters work?
If the comments should still be removed from queries anyway, then that can be added back in using the improved parser code.
Removed support for backtick quotes as those do not work in Firebolt.
Fixes #38

Fix removed "comments" from strings

---

src/formatter/index.ts
src/statement/hydrateDate.test.ts
test/unit/statement.test.ts

For a Date like `2023-01-01T00:00:00.010Z` the formatter would previously incorrectly generate `2023-01-01 00:00:00.100000`.

Fix date milliseconds formatting issue

---

.github/workflows/integration-tests.yaml

This allows us to make major releases of this Action without affecting every workflow.

ci: Using v1 tag for integration-testing-setup

---

.github/workflows/integration-tests.yaml

Update integration testing workflow to use a new setup action v2, which creates new identity engines and databases

ci: use new identity setup action

---

.github/workflows/integration-tests.yaml
src/common/api.ts
test/integration/index.test.ts
test/integration/systemEngine.test.ts

Fixes dev-go tests. `use_standard_sql` is no longer supported. Using UNNEST instead to replicate.

test: Remove deprecated set parameter

---

src/service/engine/index.ts
test/integration/engine.test.ts

Removed converting engine parameters to a string when creating engines via service

Fir 27809 services non string parameters

---

.github/workflows/release-v0.yaml
.github/workflows/release-workflow.yaml
.github/workflows/release.yaml
CHANGELOG.md
package-lock.json
package.json

Added ability for pre-release in release workflow action
- For authentication, RELEASE_PAT secret is used now, which is bound to @stepansergeevitch user
- already released 1.0.0-alpha.0 version cannot be unpublished, therefore it's a part of this change

Fir 27741 ci pre release

---

.github/workflows/release-workflow.yaml

Add `secrets: inherit` parameter to integration tests call in release action

ci: inherit secrerts in release integration tests call

---

src/formatter/index.ts
test/unit/statement.test.ts

Implement a universal bytea formatting for both standard_conforming_strings enabled and disabled

fix: bytea formatting for new ff 

---

src/connection/base.ts
src/connection/connection_v2.ts
test/unit/v2/connection.test.ts

Add support for a new system engine url format, which can contain account_id as a query_parameter as well as a part of a URL (or neither).
This assumes accounting for query parameters, that come with a system engine url, and using them later

feat: Fir 31841 dont append account id for system engine url in node sdk

---

.github/workflows/release-workflow.yaml
src/service/engine/index.ts
test/unit/v2/engine.test.ts

For CI we need to pass internal options to CREATE ENGINE query. Reading them from the environment to avoid changing the function signatures/API with rarely used parameters.

feat: Add internal options to engine create

---

src/service/engine/index.ts
test/integration/v2/engine.test.ts

Reenabled attaching database and engine for account v2. We use a different syntax now, `ALTER ENGINE .. SET DEFAULT_DATABASE=..` intead of `ATTACH ENGINE .. TO ..`

fix: reenable attach to database

---

src/service/engine/index.ts
test/unit/v2/engine.test.ts

This skips parameters that are defined as empty as well as unknown.

fix: Skip empty engine parameters

---

src/auth/index.ts
src/common/tokenCache.ts
src/http/node.ts
src/types.ts
test/unit/http.test.ts

Added in-memory token caching to node sdk since we have a lot of 429 error in tests. Also this feature should generally reduce the amount of http requests

feat: In memory token caching

---

test/integration/v2/bytea.test.ts
test/integration/v2/index.test.ts
test/integration/v2/systemEngine.test.ts

FIR-33220
Making most tests not break once we migrate the testing account to v2.
Only thing left will be to remove v1 config from resource manager tests.
- Unnest is not implemented yet so I've replaced it with a simpler query.
- Async execution is finally dropped.
- Columns default to null so one of the tests had `meta[0].type` to be `bytea null`. Not sure if expected, but to avoid this in test I'm setting it to not null explicitly.

test: Engine v2 and v1 compatible tests

---

test/unit/v1/connection.test.ts

Some basic tests to improve coverage.

test: Add connection v1 tests

---

src/common/errors.ts
src/connection/base.ts
test/integration/v2/index.test.ts
test/unit/connection.test.ts
test/unit/errors.test.ts
test/unit/v2/engine.test.ts

Somewhat hacked with `.clone()` but it seems to be a known [issue](https://github.com/node-fetch/node-fetch/issues/533).

feat(FIR-33628): Parsing composite error from response body

---

.github/workflows/integration-tests-v2.yaml
.github/workflows/nightly.yaml

version 16 is the earliest supported by us.
22 is the latest "current" version.
Odd numbered versions are not included as they have no long-term support.
More info - https://nodejs.org/en/about/previous-releases

ci: Add nightly tests

---

src/statement/hydrateResponse.ts
test/integration/v2/fetchTypes.test.ts
test/unit/statement.test.ts

Bigint is sent to us in a string in JSON so JSONParser can no longer parse it properly into an appropriate container. In this change we're checking the metadata and if not converted - convert to a BigNumber container.
Renamed boolean.test to dataType.test since it was counter-productive to keep a single test in a file.

fix(FIR-34534): Properly parsing bigint

---

.github/workflows/integration-tests-v1.yaml
.github/workflows/pull-request.yaml
.github/workflows/release-workflow.yaml
README.md
package.json

Initially attempted in #112 but some tools depend on us supporting node 16.
Standardising this across the doc and ci.

chore: set min node version to 16

---

src/connection/base.ts
src/statement/index.ts
test/integration/v1/index.test.ts
test/integration/v2/index.test.ts
test/unit/connection.test.ts

Removed copying a response object when checking for errors in json.
Now we read the response body once and reuse it everywhere. This causes the issue with streaming not working anymore. We will further think about to how fit both error handling and streaming here

fix: FIR-36189 nest js script stuck when running a query with limit 58 and above

---

test/integration/v2/index.test.ts

Previous change accidentally unskipped this test, fixing it.

test: Skip accidentally unskipped test

---

.github/workflows/integration-tests-v1.yaml
src/connection/base.ts
src/connection/connection_v1.ts
src/connection/connection_v2.ts
src/core/index.ts
src/types.ts
test/unit/connection.test.ts
test/unit/v1/connection.test.ts
test/unit/v2/connection.test.ts

This method is used by Cube.js to verify connection is working. However, every time it's used the timer on engine auto stop is reset. We want to let engine spin down despite the constant healthchecks if no other queries are running.

feat(FIR-37168): testConnection doesn't reset autostop timer

---

src/statement/dataTypes.ts
src/statement/hydrateResponse.ts
test/integration/v2/fetchTypes.test.ts
test/unit/hydrate.test.ts
test/unit/v2/statement.test.ts

Implemented the logic for struct, including allowing columns with spaces.
Added tests for struct and geography since we support it.

feat(FIR-38127): Add struct support

---

.github/workflows/pull-request.yaml
src/service/engine/model.ts

Currently when we stop an engine we check for its status, which causes it to start again if we run on that engine. This shouldn't be the case. We can safely assume if the request has succeeded that means the operation is successful. This means we can just report a Stopped state without the additional request.

fix(FIR-43473): stop engine without starting it again

---

README.md

Customers suggested it's not clear how to use Node SDK with CREATE/UPDATE/DELETE queries so I'm expanding our examples to include a more self-contained walkthrough.

docs(FIR-43258): Add examples and improve quickstart

---

src/statement/hydrateResponse.ts
test/integration/v2/fetchTypes.test.ts
test/unit/v1/statement.test.ts
test/unit/v2/statement.test.ts

Columns with nullable bigint type (`long null`) were not detected and therefore parsed properly. This change aims to fix this while also maintaining the current behaviour when metadata would contain `long null` when the column is nullable.

fix(FIR-43901): correct parsing of nullable bigint columns

---

package-lock.json
package.json
src/auth/index.ts
src/core/index.ts
test/unit/http.test.ts

Simplified diagram of the auth/execute flow before this change below. As you can see, there's a strict dependency between Authenticator and httpClient. Behind the scenes on auth failure httpclient would re-authenticate. This is where the issues arose, when concurrent requests would share an httpClient, invalidate the cache and write new values. However, since the whole process is async another request would come in, read invalidated cache value and fail to authenticate. In loop this led to many 403's stacking.
In this change we make sure that http client is not shared, which solves the issue of the race condition. Also, introducing locking mechanism to ensure we don't have multiple processes trying to authenticate at the same time.

fix(FIR-44193): auth concurrency

---

src/auth/index.ts
src/common/tokenCache.ts
src/http/node.ts
test/unit/connection.test.ts
test/unit/http.test.ts

Improving authentication mechanism.
Key Changes:
* Fix a bug in token expiry calculation
* Improved naming so it's clear what each variable represents, since there was a bug due to confusion
* Added atomic (re)authentication eliminating the possibility of the token being empty
* Improved feedback and logging so instead of sending a request that we know will fail we raise an error

fix(FIR-46131): Atomic authentication mechanism and token expiry
